### ISSUE TITLE
some usage issues

### ISSUE THREAD

**Issue by Han-YLun** [merkletreejs/merkletreejs#88]
I use this code
```
const { MerkleTree } = require('merkletreejs')
const keccak256 = require('keccak256')

const leaves =     [
    "0x7556677ca88d96B2709954ddf0A2C808e5A116D589",
    "0x7556677ca88d96B2709954f0Add2C808e5A116D339"
].map(keccak256)
const tree = new MerkleTree(leaves, keccak256,{ hashLeaves: true,sortPairs:true })
console.log(tree.toString("hex"))
```

result:
<img width="711" alt="image" src="https://github.com/merkletreejs/merkletreejs/assets/44769070/88d8c4cf-f821-4f39-9a13-c4432a9808d6">

i use website ,result is:
<img width="988" alt="image" src="https://github.com/merkletreejs/merkletreejs/assets/44769070/7691fc20-9039-4bf0-b7d9-f60ffc77cc55">

<img width="637" alt="image" src="https://github.com/merkletreejs/merkletreejs/assets/44769070/33e64f1f-bc6e-42c0-927a-4ff9e91a4498">

why is it different？

**Comment by miguelmota** [comment]
In the first example, the leaves are being double hashed. Remove the first `.map(keccak256)` from the code since `hashLeaves: true` will already hash the leaves.

```
const leaves =     [
    "0x7556677ca88d96B2709954ddf0A2C808e5A116D589",
    "0x7556677ca88d96B2709954f0Add2C808e5A116D339"
].map(keccak256) // remove this map 
```
