### ISSUE TITLE
Different result from merkletreejs and sha256

### ISSUE THREAD

**Issue by kleinpetr** [merkletreejs/merkletreejs#90]
Hi,

I am just wondering if there is any logic which I don't see because when I manually hash two hashes together the result hash is different then the output from merkletreejs

`const tree = new MerkleTree(leaves, sha256, { hashLeaves: true })`

output:
```
├─ 329b7dd2b17d26a5ee578389e64e6861da47db80a688ac7a5f0729fbaefd5848
   │  ├─ ed0d6fb1b0dbf79915f8a61a163ddbd3087a5056397c1adac85950686ab50c89
   │  └─ 1ac1a71edc321a27fed1fd6166b1f635fccc178b46e377bb24aef154179970bc
```
but when I get these two leaves hashes and join them together and use sha256 then I am getting this

```
const hash = sha256('ed0d6fb1b0dbf79915f8a61a163ddbd3087a5056397c1adac85950686ab50c891ac1a71edc321a27fed1fd6166b1f635fccc178b46e377bb24aef154179970bc')

//hash is: b03bfd00deb2fa8b29a6e8846e15315dc9d0fb1d15e67b2d6f7101ffcc793913
```

which is the same result I am getting for example from the online visualization tool https://blockchain-academy.hs-mittweida.de/merkle-tree/

Thanks for clarify

**Comment by miguelmota** [comment]
The reason is that merkletreejs treats a string that is all valid hexadecimal characters as a hex string.

![DeepinScreenshot_select-area_20240701203653](https://github.com/merkletreejs/merkletreejs/assets/168240/c36a52a2-a5c1-4d25-9912-1be6837caad6)

https://emn178.github.io/online-tools/sha256.html

If you wish to treat the input leaves as a string, convert them to a `Buffer` first:

```js
const leaves = [
  "ed0d6fb1b0dbf79915f8a61a163ddbd3087a5056397c1adac85950686ab50c89",
  "1ac1a71edc321a27fed1fd6166b1f635fccc178b46e377bb24aef154179970bc"
].map(v => Buffer.from(v))
const tree = new MerkleTree(leaves, sha256)
console.log(tree.toString())
```

```sh
└─ b03bfd00deb2fa8b29a6e8846e15315dc9d0fb1d15e67b2d6f7101ffcc793913
   ├─ 65643064366662316230646266373939313566386136316131363364646264333038376135303536333937633161646163383539353036383661623530633839
   └─ 31616331613731656463333231613237666564316664363136366231663633356663636331373862343665333737626232346165663135343137393937306263
```
